### ISSUE TITLE
*.css.map files are not served

### ISSUE THREAD

**Issue by Altai-man** [Altai-man/docs.raku.org#29]
Investigate how are they requested and write a serving route!

**Comment by raydiak** [comment]
I only checked a couple, but the maps appear to be working for me. When I inspect an element, I see the locations of the style declarations in the original sass/scss files. Since the map files are alongside the css in the same directories, they are already being handled by the existing static css route.

**Comment by Altai-man** [comment]
Hmm, maybe this issue is a bit further.

Map files appear to be served, but they disclose the structure via `sources` (e.g. `../../../ui-samples/sass/themes/_themes-template-common.scss`) and we don't serve `ui-samples/...`, which results in an inability to serve the actual sass/scss files.

OTOH I am not sure it is a 100% good idea to actually serve maps at all, opinions on this vary a lot.

**Comment by raydiak** [comment]
If you want my opinion, I think it's common for source maps to point to project paths instead of resolvable URLs including in web projects. Even on github, open dev tools on this very page right here, go to the sources tab, and find a css or js file. Nearly all of them have valid maps, but none of the mappings resolve to publicly served source files. I figure the idea is if you know the source file and line number, you'd generally rather open that in your IDE than in the browser's dev tools where you can't change it anyway.

Most of the objections to production-served map files seem be grounded in the "obscurity as security" misnomer. Even if you buy into that, it's an open-source project, so there really isn't anything being exposed which wasn't already public. I could see a small argument for server bandwidth, but unless you're close to your bandwidth allocation and have a lot of contributors using dev tools on your site, I'd call that premature optimization.

I don't personally use CSS preprocessors or minification in my own projects, so take my perspective with a grain of salt. Arguably, it's working usefully as-is.

**Comment by Altai-man** [comment]
Thanks for your opinion!

I guess let's close this and if anyone is interested it can be re-opened.
