### ISSUE TITLE
Edit page link showing even on generated pages

### ISSUE THREAD

**Issue by coke** [Altai-man/docs.raku.org#68]
e.g. http://164.90.207.89:10010/routine/now - has a link to edit which tries to go to 

https://github.com/Raku/doc/edit/master/doc/Routine/now.pod6

Can either hide edit on generated pages or maybe popup that it's a generated page.

**Comment by finanalyst** [comment]
In order to make this renderer-neutral, then the algorithm / standard for generating all pages should be specified. In principle my 'Collection' module can generate secondary pages from the primary ones. However, I haven't been able to figure out an algorithm to generate the secondary pages. At present, Documentable is the algorithm.

**Comment by Altai-man** [comment]
>Can either hide edit on generated pages

This is a better solution for now, also an easy fix.
