### ISSUE TITLE
Do we have a web host yet?

### ISSUE THREAD

**Issue by dontlaugh** [Altai-man/docs.raku.org#83]
First off, thanks for continuing to update this project.

I am curious if you've heard about where the physical infra for the next version of the site will be hosted? E.g. whether it's Linode or Digital Ocean or a physical server someone owns?

I stood up this site over the summer, and the needs are not complex. And that's a good thing! But have there been any updates? Do you know who will host the new site?

**Comment by Altai-man** [comment]
Hi!

In the past, we had some great help from members of our infra team (namely rba and maettu), but recently they decided to step down due to some personal circumstances.

I agree with you, the requirements for hosting are not that high, currently we are in need of a new volunteer, who will be willing to take over the infra and along the way host the new website (and do a redirect, etc).

**Comment by dontlaugh** [comment]
How about I start - slowly and steadily - checking in and refining deployment scripts and documentation into this repo? We can move it later when we're ready. The site that you've worked so hard on is still pre-release. But I think we will feel more productive if we run some real infra for a while.

I'll pay for the infra on my Linode account for a few months, just to get a baseline. Again, we can migrate to another host if need be.

**Comment by Altai-man** [comment]
Hmm. Let me check.

The website is already hosted on my DO droplet: http://164.90.207.89:10010
I've been paying for it since forever now.

The docker images to host are alright, there are also instructions on how to run it in README, so I am not sure to what scripts and documentation you are referring to?

If you want to step in as a volunteer for the Raku infra things, we want to notify Liz and some others. They organized a server and host management tools (podman?), so you just need to get the credentials, run the container, and ensure there is a redirect and that's it, the website works under docs.raku.org.

**Comment by dontlaugh** [comment]
cc @lizmat (I reached out to you on IRC)

**Comment by dontlaugh** [comment]
I met the rest of the infra team today and have submitted my ssh key for access to servers and my email to be added to the list. The next infra team metting is 18 January 2023.

**Comment by Altai-man** [comment]
Awesome! Are you included into the docs mailing list too? We have some talks about Richard's website being used instead.

**Comment by dontlaugh** [comment]
I have not been receiving those, no.

Update: asked coke on IRC

**Comment by dontlaugh** [comment]
Met with infra folks today; we can close this; the main priority is deploying this site, and we will first and foremost re-use existing prod infra.

We will need to work with Coke, et al on migrating the _code_. Strictly speaking we can run production from this repo under your ownership, and perhaps that's how we should start. But we will need a plan for moving this repo under Raku; Perhaps we start with a branch on the current docs repo? TBD

Wherever the code lives, we will need to design a CI pipeline that can automatically deploy changes to content and code.
